 #pragma once

#include "Camera_Default.h"
#include "Camera_First.h"
#include "Terrain.h"
#include "Fork.h"
#include "Player.h"
#include "Sword.h"
#include "NaviBox.h"
#include "ExpBall.h"
#include "Joy.h"
#include "HealBot.h"

	/*  Map  */
#include "Stage1.h"
#include "Stage2.h"
#include "Stage3.h"
#include "Stage4.h"
#include "Stage5.h"
#include "BaseCamp.h"
#include "Sky.h"
#include "MagmaTile.h"
#include "SpringBoard.h"
	/* Door */
#include "DoorStage.h"
#include "DoorBoss.h"

	/*	UI   */
#include "CrossHairRect.h"
#include "PlayerIcon.h"
#include "HealthBar.h"
#include "HealthBarBackGround.h"
#include "PlayerBackGround.h"
#include "IntroBackGround.h"
#include "IntroTag.h"
#include "FadeInOut.h"
#include "FadeOut.h"
#include "ExpBar.h"
#include "ExpBarBackGround.h"
#include "Hit.h"
#include "BossHpBarBackground.h"
#include "BossHpBar.h"
#include "Sprint.h"
#include "Recovering.h"
#include "Shield.h"
#include "RifleIcon.h"
#include "ShotgunIcon.h"
#include "BowIcon.h"
#include "BulletCount.h"
#include "BulletTenCount.h"
#include "BulletBackground.h"


	/*  Effect  */
#include "ExpTrail.h"
#include "Trail_Monster.h"
#include "Trail_Bow.h"
#include "Trail_Purple.h"
#include "MuzzleEffect.h"
#include "SmokeSprite.h"
#include "SubSmoke.h"
#include "Explosion.h"
#include "WeaponSound.h"
#include "Combine_Effect.h"
#include "Fire_Effect.h"
#include "FlameCone.h"
#include "FlameTriangle.h"
#include "RedSmoke.h"
#include "OverHit.h"
#include "OverHitLaser.h"

	/* Weapon */
#include "BundleRifle.h"
#include "BundleShotgun.h"
#include "BundleBow.h"

	/* Bullet */
#include "RifleBullet.h"
#include "ShotgunBullet.h"
#include "BowBullet.h"
#include "RocketBullet.h"
#include "CanonHitBox.h"
#include "FlameHitBox.h"
#include "MortarHitBox.h"
#include "NormalHitBox.h"
#include "StickHitBox.h"
#include "WaveHitBox.h"
#include "LaserHitBox.h"
#include "JumpingHitBox.h"
#include "EnemyBullet.h"
#include "MineHitBox.h"
#include "Punch.h"
#include "RocketExplosion.h"
#include "HandLaser.h"

	/* Enemy */
#include "BossTower.h"
#include "TowerSocle.h"
#include "BossBeetle.h"
#include "BossDisco.h"
#include "SmallBot.h"
#include "RocketPawn.h"
#include "BoomBot.h"
#include "MortarPod.h"
#include "MecanoBot.h"
#include "MinePod.h"
#include "JetFly.h"
#include "BossShield.h"